version: "3.2"
services:
  db:
    image: postgres:11.5-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    env_file:
      - ../.env.local
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "880:80"
      - "8443:443"

volumes:
  db-data:
